[package]
name = "runlet-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tower-http = { version = "0.5", features = ["trace"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
chrono = { workspace = true }
ulid = { workspace = true }
thiserror = { workspace = true }
runlet-core = { path = "../runlet-core" }
tokio-stream = { version = "0.1", features = ["sync"] }
